### ISSUE TITLE
Shellcheck warnings in packageBuildInfo.sh

### ISSUE THREAD

**Issue by finestructure** [DimaRU/PackageBuildInfo#1]
Is the source for the packaged shell script available somewhere? Shellcheck is issuing some warning around quoting:

<img width="653" alt="CleanShot 2022-09-02 at 12 38 45@2x" src="https://user-images.githubusercontent.com/65520/188122295-e8479f83-10c3-4da1-8d5b-920678fc10ba.png">

Happy to open a PR, just don't know what against 😅

**Comment by finestructure** [comment]
Here's copy of the file with suggested fixes.

[packageBuildInfo.sh.zip](https://github.com/DimaRU/PackageBuildInfo/files/9477224/packageBuildInfo.sh.zip)

**Comment by finestructure** [comment]
Hello @DimaRU - just pinging you in case you don't get notifications from issues :)

**Comment by DimaRU** [comment]
Fixed.
